Repository DO-SOPT-33rd-CDS-1/LongBlack_SERVER, pull requests merged in 2023-11, with the labels that each got.

#2 [feat] Paragraph, Bookmark, Post 엔티티 생성
  .gitignore
  gradlew
  gradlew.bat
  src/main/java/sopt/longBlack/domain/bookmark/Bookmark.java
  src/main/java/sopt/longBlack/domain/paragraph/Paragraph.java
  src/main/java/sopt/longBlack/domain/paragraph/ParagraphType.java
  src/main/java/sopt/longBlack/domain/post/Post.java
Labels: feat, 희정

#5 [feat] Stamp, Like 엔티티 생성
  src/main/java/sopt/longBlack/domain/likey/Likey.java
  src/main/java/sopt/longBlack/domain/stamp/Stamp.java
Labels: refactor, feat, 민철

#6 [feat] Post 단일 게시글 조회
  src/main/java/sopt/longBlack/controller/PostController.java
  src/main/java/sopt/longBlack/domain/post/BaseTimeEntity.java
  src/main/java/sopt/longBlack/domain/post/Post.java
  src/main/java/sopt/longBlack/domain/post/PostType.java
  src/main/java/sopt/longBlack/dto/response/SinglePostGetResponse.java
  src/main/java/sopt/longBlack/infrastructure/BookmarkRepository.java
  src/main/java/sopt/longBlack/infrastructure/ParagraphRepository.java
  src/main/java/sopt/longBlack/infrastructure/PostRepository.java
  src/main/java/sopt/longBlack/service/PostService.java
  src/main/resources/data.sql
Labels: feat, 희정

#9 [feat] Stamp 생성 및 카운트 조회 구현
  src/main/java/sopt/longBlack/controller/StampController.java
  src/main/java/sopt/longBlack/domain/post/Post.java
  src/main/java/sopt/longBlack/dto/request/StampCreateRequest.java
  src/main/java/sopt/longBlack/dto/response/StampGetResponse.java
  src/main/java/sopt/longBlack/infrastructure/StampRepository.java
  src/main/java/sopt/longBlack/service/StampService.java
  src/main/resources/data.sql
Labels: refactor, chore, feat, 민철

#11 [feat] Likey 생성 및 삭제 구현
  src/main/java/sopt/longBlack/controller/LikeyController.java
  src/main/java/sopt/longBlack/dto/request/LikeyRequest.java
  src/main/java/sopt/longBlack/infrastructure/LikeyRepository.java
  src/main/java/sopt/longBlack/service/LikeyService.java
Labels: feat, 민철

#13 [refactor] StampService Transactional 추가
  src/main/java/sopt/longBlack/service/StampService.java
Labels: refactor, 민철

#14 [refactor] 단일 게시물 조회 기능 리팩토링
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
  src/main/java/sopt/longBlack/domain/paragraph/Paragraph.java
  src/main/java/sopt/longBlack/domain/post/Post.java
  src/main/java/sopt/longBlack/dto/response/ParagraphGetResponse.java
  src/main/java/sopt/longBlack/dto/response/SinglePostGetResponse.java
  src/main/java/sopt/longBlack/infrastructure/BookmarkRepository.java
  src/main/java/sopt/longBlack/infrastructure/ParagraphRepository.java
  src/main/java/sopt/longBlack/service/PostService.java
  src/main/resources/data.sql
Labels: refactor, 희정

#19 [feat] 게시물 리스트 조회 API 구현
  src/main/java/sopt/longBlack/controller/PostController.java
  src/main/java/sopt/longBlack/domain/likey/Likey.java
  src/main/java/sopt/longBlack/dto/response/PostInfoResponse.java
  src/main/java/sopt/longBlack/dto/response/PostsGetResponse.java
  src/main/java/sopt/longBlack/service/PostService.java
  src/main/resources/data.sql
Labels: refactor, chore, feat, 민철

#17 chore: 배포용 application-dev.yml 추가
  .gitignore
  src/main/resources/application-dev.yml
Labels: chore, 민철

#20 [feat] Bookmark Post 기능 구현
  gradlew
  gradlew.bat
  src/main/java/sopt/longBlack/controller/BookmarkController.java
  src/main/java/sopt/longBlack/domain/bookmark/Bookmark.java
  src/main/java/sopt/longBlack/dto/request/BookmarkRequest.java
  src/main/java/sopt/longBlack/service/BookmarkService.java
Labels: feat, 희정

#22 [feat] Bookmark 삭제 기능 구현
  src/main/java/sopt/longBlack/controller/BookmarkController.java
  src/main/java/sopt/longBlack/service/BookmarkService.java
Labels: feat, 희정

#25 [refactor] data.sql 클라 요청사항 반영 수정
  src/main/resources/data.sql
Labels: refactor, 희정

#26 [feat] 예외 처리 구현
  src/main/java/sopt/longBlack/exception/ErrorResponse.java
  src/main/java/sopt/longBlack/exception/ErrorType.java
  src/main/java/sopt/longBlack/exception/GlobalExceptionHandler.java
  src/main/java/sopt/longBlack/exception/SuccessType.java
  src/main/java/sopt/longBlack/infrastructure/BookmarkRepository.java
  src/main/java/sopt/longBlack/service/BookmarkService.java
  src/main/java/sopt/longBlack/service/PostService.java
Labels: feat, 희정
